### ISSUE TITLE
WIKI信息过时？

### ISSUE THREAD

**Issue by misaka10843** [Akashic-Server/wiki.akashic.cc#1]
![图片](https://user-images.githubusercontent.com/69132853/159266544-557d65ae-a93b-4c7c-8188-e36f0e2c93de.png)
理论来说服务器应该到达di三周目并且版本升级到1.18.1

但是Wiki中却还停留在二周目并且版本为1.17

虽然不知道开发者是否还在维护，但是本人认为最好还是先更新一下比较好

如果您觉得麻烦，还请您关闭此issue，请谅解

**Comment by Mythologyli** [comment]
感谢提醒，有空更新

**Comment by misaka10843** [comment]
> 感谢提醒，有空更新

好的，麻烦大大了qwq
